import { defineConfig } from "orval";

export default defineConfig({
  sigflow: {
    input: {
      target: "http://localhost:3000/swagger/json",
      validation: false,
    },
    output: {
      mode: "split",
      target: "./src/generated/api.ts",
      schemas: "./src/generated/models",
      client: "svelte-query",
      mock: true,
      prettier: true,
      override: {
        mutator: {
          path: "./src/generated/api-client.ts",
          name: "customInstance",
        },
        query: {
          useQuery: true,
          useMutation: true,
          version: 5,
          options: {
            staleTime: 10000,
          },
        },
        header: (info) => [
          "/**",
          ` * Generated by orval v${info.version} 🍺`,
          " * Do not edit manually.",
          " * Sigflow API",
          " * OpenAPI spec version: 0.1.0",
          " */",
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: "prettier --write",
    },
  },
});
