version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ottobot-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - ottobot-dev-network

  # Development setup - run API and worker locally with bun --watch
  # Only Redis runs in Docker for development

volumes:
  redis-dev-data:

networks:
  ottobot-dev-network:
    driver: bridge